In [3]:
import numpy as np


In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr0=np.array([5, 10, 15, 20, 25])
arr0.sum()
arr0.mean()

np.float64(15.0)

In [24]:
list=[]
for i in range(0,20):
    if i%2==0:
        list.append(i)
        arr1=np.array(list)

In [25]:
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
arr2=np.array([10,20,30,40,50,60,70])

In [42]:
arr2[0:3]
arr2[-2:]
arr2[1:5]

array([20, 30, 40, 50])

In [43]:
arr3=[[1,2,3],
 [4,5,6],
 [7,8,9]]

In [48]:
arr3[1]


[4, 5, 6]

In [50]:
arr5 = np.arange(1,21,5)

In [53]:
arr5
print(arr5**2)
arr5.shape

[  1  36 121 256]


(4,)

In [61]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [64]:
arr[:,3]
arr[:,1]
arr[2]

array([ 9, 10, 11, 12])

In [1]:
import numpy as np

In [7]:
arr6=np.arange(0,9)

In [8]:
arr6.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr7=np.arange(0,16)


In [10]:
arr7.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
arr7[1]

np.int64(1)

In [15]:
arr8=np.arange(0,25)

In [22]:
arr9=arr8.reshape(5,5)

In [24]:
arr9[3]

array([15, 16, 17, 18, 19])