In [3]:
import numpy as np


In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr0=np.array([5, 10, 15, 20, 25])
arr0.sum()
arr0.mean()

np.float64(15.0)

In [24]:
list=[]
for i in range(0,20):
    if i%2==0:
        list.append(i)
        arr1=np.array(list)

In [25]:
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
arr2=np.array([10,20,30,40,50,60,70])

In [42]:
arr2[0:3]
arr2[-2:]
arr2[1:5]

array([20, 30, 40, 50])

In [43]:
arr3=[[1,2,3],
 [4,5,6],
 [7,8,9]]

In [48]:
arr3[1]


[4, 5, 6]

In [50]:
arr5 = np.arange(1,21,5)

In [53]:
arr5
print(arr5**2)
arr5.shape

[  1  36 121 256]


(4,)

In [61]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [64]:
arr[:,3]
arr[:,1]
arr[2]

array([ 9, 10, 11, 12])

In [1]:
import numpy as np

In [7]:
arr6=np.arange(0,9)

In [8]:
arr6.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr7=np.arange(0,16)


In [10]:
arr7.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
arr7[1]

np.int64(1)

In [15]:
arr8=np.arange(0,25)

In [22]:
arr9=arr8.reshape(5,5)

In [24]:
arr9[3]

array([15, 16, 17, 18, 19])

In [31]:
arr10=np.arange(0,288)
arr10


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [32]:
arr11=arr10.reshape(2,3,2,6,4)

In [33]:
arr11

array([[[[[  0,   1,   2,   3],
          [  4,   5,   6,   7],
          [  8,   9,  10,  11],
          [ 12,  13,  14,  15],
          [ 16,  17,  18,  19],
          [ 20,  21,  22,  23]],

         [[ 24,  25,  26,  27],
          [ 28,  29,  30,  31],
          [ 32,  33,  34,  35],
          [ 36,  37,  38,  39],
          [ 40,  41,  42,  43],
          [ 44,  45,  46,  47]]],


        [[[ 48,  49,  50,  51],
          [ 52,  53,  54,  55],
          [ 56,  57,  58,  59],
          [ 60,  61,  62,  63],
          [ 64,  65,  66,  67],
          [ 68,  69,  70,  71]],

         [[ 72,  73,  74,  75],
          [ 76,  77,  78,  79],
          [ 80,  81,  82,  83],
          [ 84,  85,  86,  87],
          [ 88,  89,  90,  91],
          [ 92,  93,  94,  95]]],


        [[[ 96,  97,  98,  99],
          [100, 101, 102, 103],
          [104, 105, 106, 107],
          [108, 109, 110, 111],
          [112, 113, 114, 115],
          [116, 117, 118, 119]],

         [[120, 121, 122, 

In [37]:
arr11.ndim
1
33
58
102
143
215

215

In [43]:
arr11[0,0,0,0,1]

np.int64(1)

In [49]:
arr11[0,0,1,2,1]

np.int64(33)

In [54]:
arr11[0,1,0,2,2]

np.int64(58)

In [60]:
arr11[0,2,0,1,2]

np.int64(102)

In [67]:
arr11[0,2,1,5,3]

np.int64(143)

In [74]:
arr11[1,1,0,5,3]

np.int64(215)

In [89]:
arr12=np.arange(0,60)

In [90]:
arr13=arr12.reshape(2,5,6)

In [92]:
arr13

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]]])

In [97]:
arr13[0,3: ,4:]

array([[22, 23],
       [28, 29]])

In [88]:
#long matrix ke slicing ka lia hum pahla row oska bad coulm

In [ ]:
arr13[3: ,4:]