In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [6]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones([2,45])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
np.linspace(2,3,7)

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        ])

In [9]:
np.random.rand(2,3)

array([[0.36814825, 0.76027163, 0.16174807],
       [0.75400186, 0.03137228, 0.42140189]])

In [10]:
arr.size

6

In [11]:
arr.shape

(6,)

In [12]:
arr.dtype

dtype('int64')

In [13]:
arr.ndim

1

Array methods

In [14]:
arr.max()



np.int64(6)

In [15]:
arr.min()

np.int64(1)

In [16]:
arr.std()

np.float64(1.707825127659933)

In [17]:
arr.argmax()

np.int64(5)

In [18]:
arr.argmin()

np.int64(0)

Reshape and resize of array

In [20]:
arr2=np.arange(0,31)

In [26]:
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])