1. The Multi-Line Story: Print a short story (3 lines) using only one print() statement.

In [2]:
from asyncio import wait

import numpy as np

print("""A boy found an old key in his garden
He tried it on a locked box in his house.
Inside, he discovered his grandfather’s hidden treasure.
""")


A boy found an old key in his garden
He tried it on a locked box in his house.
Inside, he discovered his grandfather’s hidden treasure.



2. The Border: Print the word "PYTHON" surrounded by a box made of asterisks (*).

In [3]:
print("*********")
print(" Python ")
print("*********")

*********
 Python 
*********


3. The Separator: Use the sep parameter to print the numbers 1 through 5 separated by
arrows (e.g., 1 -> 2 -> 3).

In [4]:
print(1,2,3,4,5,sep=" ->")


1 ->2 ->3 ->4 ->5


4. The End Game: Print two separate sentences on the same line using the end
parameter.

In [5]:
print("my name is umar",end=" ")
print("I am student")

my name is umar I am student


5. The Formatter: Print a decimal number (like 12.34567) rounded to exactly two decimal
places using an f-string.

In [6]:
decnum=12.34567
print(f"{decnum:.2f}")

12.35


2. The input() Function

1. The Greeter: Ask for a name and a favorite color, then print: "Hi [Name], [Color] looks
great on you!"

In [7]:
name = input("Enter your name: ")
color = input("Enter your favorite color: ")
print(f"Hi {name}, {color} looks great on you")

Hi UmarFarooq, White looks great on you


2. The Age Gap: Ask for the user's age and print how old they will be in the year 2050.

In [8]:
age=int(input("enter your age"))
current_year=int(input("enter your current year"))
future_age=age+(2050-current_year)
print(f"In 2050 you will be {future_age} years old")

In 2050 you will be 44 years old


3. The Multiplier: Ask for two numbers, multiply them, and print the result. (Watch out for
string vs. integer errors!)

In [9]:
num1=int(input("enter your first number"))
num2=int(input("enter your second number"))
print(num1*num2)

600


4. The Repeater: Ask for a word and a number, then print that word as many times as the
number specifies.

In [10]:
word=input("enter your word")
num=int(input("enter your number"))
print(num*word)

UmarUmarUmar


5. The Bill Splitter: Ask for a total bill amount and the number of people. Print how much
each person owes.

In [11]:
totalbill=int(input("enter total bill of amount"))
people=int(input("enter number of people"))
print(f"{totalbill/people}")


750.0


3. Operators

1. The Remainder: Ask for two numbers and print only the remainder when the first is
divided by the second.

In [12]:
num1=int(input("enter your first number"))
num2=int(input("enter your second number"))
print(f"number one:{num1} and number two: {num2}and its Remainder:{num1%num2} ")

number one:20 and number two: 30and its Remainder:20 


2. The Power: Write a program that calculates $x^y$ where $x$ and $y$ are user inputs.

In [1]:
x=int(input("enter your first number"))
y=int(input("enter your second number"))
print(f"{x**y}")


8916100448256


3. The Floor: Perform "floor division" on two numbers and explain why the result is an
integer.

In [2]:
num1=int(input("enter your first number"))
num2=int(input("enter your second number"))
print(f"{num1//num2}")


0


4. The Comparison: Ask for a number and print True if it is greater than 100 and False
otherwise (without using an if statement).

In [3]:
num = int(input("Enter a number: "))
print(num > 100)


False


5. The Swapper: Use operators to swap the values of two variables $a$ and $b$ without
using a third temporary variable.

In [4]:
a=10
b=15
a,b=a,b
print("a=",a)
print("b=",b)


a= 10
b= 15


4. Variables

1. The Scoreboard: Create a variable score starting at 0. Update it by 10, then decrease it
by 3, and print the final value

In [5]:
score=0
score+=10
score-=3
print(score)

7


2. The Constant: Create a variable for PI (3.14159) and calculate the area of a circle
based on a user-provided radius.

In [6]:
pi=3.14159
radius=int(input("enter radius "))
area=pi*radius*radius
print(area)

78.53975


3. The Concatenator: Store a first name and a last name in different variables, then
combine them into a full_name variable.

In [7]:
first_name="umar"
last_name="farooq"
full_name=first_name+last_name
print(full_name)

umarfarooq


4. The Type Checker: Create three variables (a string, an integer, and a float) and print the
type() of each.

In [8]:
name="umar"
age=20
height=5.6
print(type(name))
print(type(age))
print(type(height))

<class 'str'>
<class 'int'>
<class 'float'>


5. The Dynamic Type: Assign a number to a variable, print it, then assign a string to that
same variable and print it again. 

In [9]:
name=20
print(name)
name="umar"
print(name)


20
umar


5. IF / ELSE

1. Odd or Even: Ask for a number and tell the user if it is even or odd.

In [10]:
num=int(input("enter the number"))
if num%2==0:
    print("even number")
else:
    print("odd number")

even number


2. The Grade Book: Take a score (0-100) and print "A" for 90+, "B" for 80+, and "F" for
anything below 60.

In [11]:
score=int(input("enter the score"))
if score>=90 :
    print("A+")
elif score>=80 :
    print("B+")
elif score<=60 :
    print("F+")
else:
    print("F")

A+


3. The Bouncer: Ask for a user's age. If they are 18 or older, say "Enter"; otherwise, tell
them how many years they have to wait.

In [12]:
age=int(input("enter your age"))
if age>=18:
    print("Enter")
else:
    wait=18-age
    print(f"wait {wait}  years. ")


Enter


4. The Password: Create a "secret password" variable. Ask the user for input; if it
matches, print "Access Granted."

In [13]:
secret_password="umar0101"
password=input("enter your password")
if secret_password==password:
    print("Access Granted.")
else:
    print("Wrong Password.")


Wrong Password.


5. Leap Year: Ask for a year and determine if it is a leap year (divisible by 4 but not 100,
unless divisible by 400).

In [14]:
year = int(input("Enter year: "))

if year % 400 == 0:
    print("Leap year")
elif year % 100 == 0:
    print("Not leap year")
elif year % 4 == 0:
    print("Leap year")
else:
    print("Not leap year")


Not leap year


6. Loops

1. The Countdown: Use a while loop to count down from 10 to 1 and then print "Blast off!"


In [15]:
number = 10
while number >= 1:
    print(number)
    number -= 1
print("Blast off")

10
9
8
7
6
5
4
3
2
1
Blast off


2 The Multiples: Use a for loop to print the first 10 multiples of 5.

In [16]:
for i in range(1,11):
    print(i*5)

5
10
15
20
25
30
35
40
45
50


3. The Accumulator: Write a loop that asks the user for numbers until they type "0", then
print the total sum of all numbers entered. 

In [19]:
sum = 0

while True:
    num = int(input("Enter a number: "))

    if num == 0:
        break

    sum = sum + num

print("Total sum is:", sum)

Total sum is: 0


4. The Searcher: Loop through a string and count how many times the letter "a" appears.

In [20]:

stri = input("Enter your string: ")
count = 0

for i in stri:
    if i == "a":
        count = count + 1

print("Total 'a' letters:", count)


Total 'a' letters: 1


5. The Breakout: Write an infinite loop that only stops (break) when the user types the
word "stop".

In [21]:
while True:
    print("word")
    com=input("Enter a word: stop")
    if com=="stop":
        break

word
word
word


7. Data Structures (Lists/Tuples/Dicts)

1. The Grocery List: Create a list of 5 items. Replace the second item with "Milk" and
remove the last item.

In [26]:
groclist=["Onions","Rice","Milk","Bread","Eggs"]
groclist[1]="Milk"
groclist.remove("Eggs")

print(groclist)

['Onions', 'Milk', 'Milk', 'Bread']


2. The Slicer: Given a list of 10 numbers, print only the middle four numbers using slicing.


In [28]:
num=[1,2,3,4,5,6,7,8,9,10]
sli=num[4:7]
print(sli)

[5, 6, 7]


3. The Dictionary: Create a dictionary of a "Phone Book" with 3 names and numbers. Print
only the phone number of a specific name.

In [32]:
phonebook={"umar":"0304",
            "ali":"0345",
            "farooq":"0346"}
print(phonebook["umar"])

0304


4. The Unique List: Given a list with duplicate numbers, create a new list (or set) that
contains only the unique values.

In [34]:
d=[1, 2, 2, 3, 4, 4, 5]
f=set(d)
print(f)

{1, 2, 3, 4, 5}


5. The Coordinator: Create a tuple representing coordinates $(x, y)$. Try to change the
$x$ value and explain why Python throws an error.

In [35]:
coordinates = (10, 20)
coordinates[0] = 50

print(coordinates)

TypeError: 'tuple' object does not support item assignment

8. NumPy (Multidimensional & Indexing)

1. The Matrix: Create a $3 \times 3$ NumPy array containing the numbers 1 through 9.


In [37]:
import numpy as np

In [40]:
f=np.arange(1,10).reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2. The Corner: From a $4 \times 4$ array, use indexing to extract the value in the top-right
corner.

In [45]:
s=np.arange(0,16).reshape(4,4)
s[0,0]

np.int64(0)

3. The Row Picker: Create a $5 \times 5$ array of random numbers and print only the 3rd
row.

In [49]:
g=np.arange(0,25).reshape(5,5)
g[2]


array([10, 11, 12, 13, 14])

4. The Sub-Grid: From a $6 \times 6$ array, extract a $2 \times 2$ "sub-matrix" from the
center.

In [55]:
h=np.arange(0,36).reshape(6,6)
h[2:4,2:4]

array([[14, 15],
       [20, 21]])

5. The Zero-Out: Create a $3 \times 3$ identity matrix (1s on the diagonal) and use
indexing to change the center value to 10.

In [57]:

matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
