In [1]:
import numpy as np

Task 2: Create NumPy Arrays

1. A 1D array containing numbers from 1 to 10

In [2]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

A 2D array of 3 rows and 3 columns

In [5]:
arr=np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3: An array filled with zeros (5 elements)

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

An array filled with ones (5 elements)

In [7]:
np.ones(5)


array([1., 1., 1., 1., 1.])

Task 3: Basic Array Operations

In [12]:
a= [1,2,3,4,5]
b = [5,4,3,2,1]
arr1=np.array(a)
arr2=np.array(b)


1. Addition

In [13]:
arr1+arr2

array([6, 6, 6, 6, 6])

2. Subtraction

In [14]:
arr1-arr2

array([-4, -2,  0,  2,  4])

3. Multiplication

In [16]:
arr1*arr2

array([5, 8, 9, 8, 5])

4. Division

In [17]:
arr1/arr2

array([0.2, 0.5, 1. , 2. , 5. ])

Task 4: Array Information

In [23]:
arr=np.arange(1,21)
arr.shape
arr.dtype
arr.size

20

Task 5: Indexing

In [24]:
arr1=np.array([10,20,30,40,50,60,70] )

In [25]:
arr1[0]

np.int64(10)

In [26]:
arr1[-1]

np.int64(70)

In [27]:
arr1[1:5]

array([20, 30, 40, 50])

Part 2 — Intermediate Level

Task 6: Random Arrays

In [29]:
arra=np.arange(0,16).reshape(4,4)

1. Minimum value


In [31]:
arra.min()

np.int64(0)

2. Maximum value

In [32]:
arra.max()

np.int64(15)

3. Mean (average)

In [34]:
arra.mean()

np.float64(7.5)

4. Sum of all elements

In [35]:
arra.sum()

np.int64(120)

Task 7: Reshaping Arrays

In [38]:
arr4=np.arange(1,13).reshape((3,4))
arr5=np.arange(1,13).reshape((4,3))

In [39]:
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
arr5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Task 8: Matrix Operations

In [47]:
arr1=np.arange(0,6).reshape(2,3)
arr1
arr2=np.arange(6,12).reshape(2,3)
arr2




array([[ 6,  7,  8],
       [ 9, 10, 11]])

1. Matrix addition

In [49]:
arr1+arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

2. Matrix subtraction

In [50]:
arr1-arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

3. Element-wise multiplication

In [54]:
r=arr1@arr2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

Task 9: Filtering Data


In [55]:
arr3=np.arange(1-30)

In [58]:
arr3[[arr3>30]]

array([], shape=(1, 0), dtype=int64)